Semicolon To Handle Uncaught TypeError
Insert semicolon to handle uncaught type error undefined is not a function. This is due to missing semicolon(s) in loaded libraries such as jQuery.